package py.com.systven.view;

import javax.swing.*;
import py.com.systven.view.ClienteView;
import py.com.systven.view.DepartamentoView;
import py.com.systven.view.UnidadProductoView;
import utilitarios.*;

public class ventanaprincipal extends javax.swing.JFrame {
    data mostrar_datos;
    String set_look = "com.sun.java.swing.plaf.metal.MetalLookAndFeel";
    /** Creates new form ventanaprincipal */
    public ventanaprincipal() {
        initComponents();
        mostrar_datos = new data();
        mostrar_datos.el_dato();
        lbl_data.setText("Hoy es "+mostrar_datos.dia_semana+ " "+mostrar_datos.dia+" de "+mostrar_datos.mes+" del año "+mostrar_datos.anho);
        timer1.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        lbl_data = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_cliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Registros = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_direccion = new javax.swing.JMenuItem();
        jmi_telefono = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_tipo_de_pago = new javax.swing.JMenuItem();
        jmi_funcionarios = new javax.swing.JMenuItem();
        jmi_cargo = new javax.swing.JMenuItem();
        jmi_departamento = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_proveedores = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmi_producto = new javax.swing.JMenuItem();
        jmi_unidad = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmin_salir = new javax.swing.JMenuItem();
        Menu_Movimiento = new javax.swing.JMenu();
        jmi_ventas = new javax.swing.JMenuItem();
        jmi_presupuesto = new javax.swing.JMenuItem();
        Menu_Reportes = new javax.swing.JMenu();
        jmi_reporte_de_ventas = new javax.swing.JMenuItem();
        Menu_Utilitarios = new javax.swing.JMenu();
        jmi_look_and_fell_nimbus = new javax.swing.JMenuItem();
        jmi_look_and_fell_liquid = new javax.swing.JMenuItem();
        Menu_Seguridad = new javax.swing.JMenu();
        jmi_cambiar_contraseña_actual = new javax.swing.JMenuItem();
        jmi_nivel_acceso = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");

        lbl_data.setText("Fecha.:");

        lbl_hora.setText("Hora.:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/user-32.png"))); // NOI18N
        btn_cliente.setText("Cliente");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/politecnica.png"))); // NOI18N

        Menu_Registros.setText("Registros");

        jmi_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmi_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/clientes.png"))); // NOI18N
        jmi_cliente.setText("Cliente");
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        Menu_Registros.add(jmi_cliente);

        jmi_direccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmi_direccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/ciudad.png"))); // NOI18N
        jmi_direccion.setText("Dirección ");
        Menu_Registros.add(jmi_direccion);

        jmi_telefono.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jmi_telefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/barrio.png"))); // NOI18N
        jmi_telefono.setText("Teléfono");
        Menu_Registros.add(jmi_telefono);
        Menu_Registros.add(jSeparator1);

        jmi_tipo_de_pago.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jmi_tipo_de_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/icon-money.png"))); // NOI18N
        jmi_tipo_de_pago.setText("Tipo de Pago");
        Menu_Registros.add(jmi_tipo_de_pago);

        jmi_funcionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmi_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/funcionario.png"))); // NOI18N
        jmi_funcionarios.setText("Funcionarios");
        Menu_Registros.add(jmi_funcionarios);

        jmi_cargo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmi_cargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/cargo.png"))); // NOI18N
        jmi_cargo.setText("Cargo");
        Menu_Registros.add(jmi_cargo);

        jmi_departamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmi_departamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/world.png"))); // NOI18N
        jmi_departamento.setText("Departamento");
        jmi_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_departamentoActionPerformed(evt);
            }
        });
        Menu_Registros.add(jmi_departamento);
        Menu_Registros.add(jSeparator2);

        jmi_proveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmi_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/user-32.png"))); // NOI18N
        jmi_proveedores.setText("Proveedores");
        Menu_Registros.add(jmi_proveedores);
        Menu_Registros.add(jSeparator3);

        jmi_producto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmi_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/folder_camera.png"))); // NOI18N
        jmi_producto.setText("Producto");
        Menu_Registros.add(jmi_producto);

        jmi_unidad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        jmi_unidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/wrench_orange.png"))); // NOI18N
        jmi_unidad.setText("Unidad");
        jmi_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_unidadActionPerformed(evt);
            }
        });
        Menu_Registros.add(jmi_unidad);
        Menu_Registros.add(jSeparator4);

        jmin_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmin_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/salir.png"))); // NOI18N
        jmin_salir.setText("Salir");
        jmin_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmin_salirMouseClicked(evt);
            }
        });
        jmin_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmin_salirActionPerformed(evt);
            }
        });
        Menu_Registros.add(jmin_salir);

        jMenuBar1.add(Menu_Registros);

        Menu_Movimiento.setText("Movimiento");

        jmi_ventas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jmi_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/getmoney.png"))); // NOI18N
        jmi_ventas.setText("Ventas");
        Menu_Movimiento.add(jmi_ventas);

        jmi_presupuesto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmi_presupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/money.png"))); // NOI18N
        jmi_presupuesto.setText("Presupuesto");
        Menu_Movimiento.add(jmi_presupuesto);

        jMenuBar1.add(Menu_Movimiento);

        Menu_Reportes.setText("Reportes");

        jmi_reporte_de_ventas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmi_reporte_de_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/relatorio.png"))); // NOI18N
        jmi_reporte_de_ventas.setText("Reporte de Ventas");
        Menu_Reportes.add(jmi_reporte_de_ventas);

        jMenuBar1.add(Menu_Reportes);

        Menu_Utilitarios.setText("Utilitarios");

        jmi_look_and_fell_nimbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmi_look_and_fell_nimbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/application_double.png"))); // NOI18N
        jmi_look_and_fell_nimbus.setText("Look and Fell_Nimbus");
        jmi_look_and_fell_nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_look_and_fell_nimbusActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(jmi_look_and_fell_nimbus);

        jmi_look_and_fell_liquid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmi_look_and_fell_liquid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/table.png"))); // NOI18N
        jmi_look_and_fell_liquid.setText("Look and Fell_Liquid");
        jmi_look_and_fell_liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_look_and_fell_liquidActionPerformed(evt);
            }
        });
        Menu_Utilitarios.add(jmi_look_and_fell_liquid);

        jMenuBar1.add(Menu_Utilitarios);

        Menu_Seguridad.setText("Seguridad");

        jmi_cambiar_contraseña_actual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmi_cambiar_contraseña_actual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/lock.png"))); // NOI18N
        jmi_cambiar_contraseña_actual.setText("Cambiar Contraseña Actual");
        Menu_Seguridad.add(jmi_cambiar_contraseña_actual);

        jmi_nivel_acceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmi_nivel_acceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysvent/imagenes/key_delete.png"))); // NOI18N
        jmi_nivel_acceso.setText("Nivel de Acceso");
        Menu_Seguridad.add(jmi_nivel_acceso);

        jMenuBar1.add(Menu_Seguridad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_hora)
                            .addComponent(lbl_data)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, 0, 0, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(281, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(218, 218, 218)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(lbl_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_hora)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(150, 150, 150)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-515)/2, (screenSize.height-400)/2, 515, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        mostrar_datos.leer_hora();
        lbl_hora.setText("Hora actual: "+mostrar_datos.hora);
    }//GEN-LAST:event_timer1OnTime

    private void jmi_look_and_fell_nimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_look_and_fell_nimbusActionPerformed
        set_look = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
        lookandfeel();    // TODO add your handling code here:
    }//GEN-LAST:event_jmi_look_and_fell_nimbusActionPerformed

    private void jmi_look_and_fell_liquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_look_and_fell_liquidActionPerformed
        set_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();// TODO add your handling code here:
    }//GEN-LAST:event_jmi_look_and_fell_liquidActionPerformed

    private void jmin_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmin_salirMouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jmin_salirMouseClicked

    private void jmi_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_unidadActionPerformed
        String args[]=new String[1];
        args[0]="Registro de Unidad de Producto";
        UnidadProductoView.main(args);      // TODO add your handling code here:
    }//GEN-LAST:event_jmi_unidadActionPerformed

    private void jmi_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_departamentoActionPerformed
          String args[] = new String[1];
          args[0] = "Registro de Departamento";
          DepartamentoView.main(args);      // TODO add your handling code here:
    }//GEN-LAST:event_jmi_departamentoActionPerformed

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
            String args[] = new String[1];//creamos un vector aquí de una sola posición;
            args[0] = "Registro de Clientes";//es este el parámetro que le pasamos a nuestro método main
            ClienteView.main(args);    // TODO add your handling code here:
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jmin_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmin_salirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jmin_salirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Movimiento;
    private javax.swing.JMenu Menu_Registros;
    private javax.swing.JMenu Menu_Reportes;
    private javax.swing.JMenu Menu_Seguridad;
    private javax.swing.JMenu Menu_Utilitarios;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem jmi_cambiar_contraseña_actual;
    private javax.swing.JMenuItem jmi_cargo;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_departamento;
    private javax.swing.JMenuItem jmi_direccion;
    private javax.swing.JMenuItem jmi_funcionarios;
    private javax.swing.JMenuItem jmi_look_and_fell_liquid;
    private javax.swing.JMenuItem jmi_look_and_fell_nimbus;
    private javax.swing.JMenuItem jmi_nivel_acceso;
    private javax.swing.JMenuItem jmi_presupuesto;
    private javax.swing.JMenuItem jmi_producto;
    private javax.swing.JMenuItem jmi_proveedores;
    private javax.swing.JMenuItem jmi_reporte_de_ventas;
    private javax.swing.JMenuItem jmi_telefono;
    private javax.swing.JMenuItem jmi_tipo_de_pago;
    private javax.swing.JMenuItem jmi_unidad;
    private javax.swing.JMenuItem jmi_ventas;
    private javax.swing.JMenuItem jmin_salir;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_hora;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
public void lookandfeel()
{
try
{
//La variable set look tiene que estar definida arriba como una variable String
UIManager.setLookAndFeel(set_look);
SwingUtilities.updateComponentTreeUI(this);
}
catch (Exception error)
{
JOptionPane.showMessageDialog(null, error);
} }
}
